import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { cases } from '../content/cases.mjs';
import { recipient } from '../content/contact.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const esc = (value = '') => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const external = (url, label, className = 'text-link') => `<a class="${className}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label} <span aria-hidden="true">↗</span><span class="sr-only"> (새 탭)</span></a>`;
const logo = `<span class="wordmark"><img src="/assets/brand-mark.svg" width="34" height="34" alt="">typeworks<span class="brand-period">.</span></span>`;
const navItems = [['/', '홈'], ['/about/', '회사 소개'], ['/services/', '제품 제작'], ['/work/', '제작 사례']];
const header = active => `<a class="skip-link" href="#main">본문으로 이동</a><header class="site-header wrap"><a class="brand" href="/" aria-label="타입웍스 홈">${logo}</a><button class="menu-toggle" type="button" aria-controls="site-navigation" aria-expanded="false"><span>메뉴</span><span class="menu-lines" aria-hidden="true"></span></button><nav id="site-navigation" aria-label="주 메뉴">${navItems.map(([url, label]) => `<a href="${url}"${active === url ? ' aria-current="page"' : ''}>${label}</a>`).join('')}<a class="nav-contact" href="/contact/"${active === '/contact/' ? ' aria-current="page"' : ''}>제작 상담 <span aria-hidden="true">↗</span></a><a class="language-link" href="/en/" lang="en" aria-label="기존 영문 포트폴리오">EN</a></nav></header>`;
const footer = `<footer class="site-footer wrap"><div><a class="brand" href="/" aria-label="타입웍스 홈">${logo}</a><p>필요를 정의하고, 작동하는 제품으로.</p></div><div class="footer-links"><a href="/about/">회사 소개</a><a href="/services/">제품 제작</a><a href="/contact/">제작 상담</a>${external('https://www.linkedin.com/in/type-types', 'LinkedIn', '')}</div><div class="footer-bottom"><span>타입웍스 / 대표 박민석 / Seoul, Korea</span><span>© 2026 Typeworks</span></div></footer>`;
const cta = (title = '필요한 것부터<br>함께 이야기해 보세요.') => `<section class="contact-band"><div class="wrap"><span class="eyebrow">LET’S MAKE IT WORK</span><div class="contact-band-bottom"><h2>${title}</h2><a class="button light" href="/contact/">제작 상담 시작하기 <span aria-hidden="true">↗</span></a></div></div></section>`;
const pageIntro = (eyebrow, title, description) => `<section class="page-intro wrap"><span class="eyebrow blue-label">${eyebrow}</span><h1>${title}</h1><p class="intro-description">${description}</p></section>`;
const sectionHead = (number, label, title, description = '') => `<div class="section-head"><span class="eyebrow"><span class="section-number">${number}</span>${label}</span><div class="section-copy"><h2>${title}</h2>${description ? `<p class="section-description">${description}</p>` : ''}</div></div>`;

const technologySection = `<section class="technology-section" id="technology" aria-labelledby="technology-title"><h2 class="technology-title" id="technology-title">제품에 연결할 수 있는 기술</h2><div class="technology-list"><article class="technology-item"><span class="eyebrow blue-label">NFC / NTAG 424 DNA</span><h3>지문 인식기 없이,<br>현장 방문 확인</h3><p>고가의 지문 인식기를 설치하는 대신, 휴대전화로 NFC 태그를 확인하는 방문 검증 모듈을 보유하고 있습니다. 고객의 방문 확인과 기록 흐름에 연결합니다.</p></article><article class="technology-item"><span class="eyebrow blue-label">AI / SIP 전화 연결</span><h3>AI가 먼저 전화하고,<br>사용자와 대화</h3><p>SIP 전화 연결을 통해 AI가 사용자에게 전화를 거는 기술을 보유하고 있습니다. 필요한 발신 통화와 AI 대화 기능을 제품에 연결합니다.</p><a class="text-link" href="/work/ondam/">AI 안부전화 제작 경험 보기 <span aria-hidden="true">↗</span></a></article></div></section>`;

function flowGraphic(kind) {
  if (kind === 'csi') return `<div class="flow-visual csi-flow" aria-label="센서와 영상 기록에서 라벨링으로 이어지는 데이터 흐름"><div class="visual-label"><span>CSI DATA WORKFLOW</span><span>데이터 수집과 라벨링</span></div><div class="signal-lines" aria-hidden="true"><svg viewBox="0 0 520 120" fill="none"><path d="M0 60L25 60L38 29L52 88L66 40L82 67L108 60L143 60L157 15L172 106L189 38L205 76L225 59L254 61L277 60L294 39L308 77L324 47L348 60L375 60L392 23L408 96L426 34L441 73L462 60L520 60" stroke="currentColor" stroke-width="2"/></svg></div><div class="flow-stages"><span>센서 + 영상 기록</span><i aria-hidden="true">→</i><span>동기화</span><i aria-hidden="true">→</i><span>행동 라벨링</span></div><div class="timeline" aria-hidden="true"><span>00:00</span><div><i></i><i></i><i></i><i></i><i></i></div><span>00:30</span></div><p class="visual-note">제품의 데이터 흐름을 설명한 도식입니다.</p></div>`;
  if (kind === 'ignition') return `<div class="flow-visual stage-flow"><div class="visual-label"><span>IGNITION / LIVE</span><span>공연 참여 흐름</span></div><div class="stage-title"><span>ON STAGE</span><strong>함께 만드는<br>공연의 순간.</strong></div><div class="stage-controls"><span>현재 공연</span><span>응원 보내기</span><span>채팅과 추첨</span></div><p class="visual-note">공연 참여 기능을 설명한 도식입니다.</p></div>`;
  return `<div class="flow-visual simple-flow"><div class="visual-label"><span>${esc(kind)}</span><span>PROJECT EXPERIENCE</span></div><div class="simple-flow-title">필요를 이해하고<br>사용할 수 있는 형태로.</div><div class="flow-stages"><span>요구 정의</span><i aria-hidden="true">→</i><span>제작</span><i aria-hidden="true">→</i><span>사용 확인</span></div></div>`;
}

function caseVisual(item) {
  if (item.slug === 'melissa') return `<div class="app-visual"><span class="visual-label">MELISSA / AI JOURNALING</span><div class="app-gallery">${[1, 2, 3].map(n => `<img src="/assets/melissa-${n}.webp" alt="멜리사 공식 앱스토어 소개 화면 ${n}" width="221" height="480" loading="lazy">`).join('')}</div><span class="visual-note">공식 앱스토어 소개 화면</span></div>`;
  if (item.image) return `<div class="screen-visual"><div class="visual-label"><span>${esc(item.title)}</span><span>실제 제품 화면</span></div><div class="browser-frame"><div class="browser-bar" aria-hidden="true"><i></i><i></i><i></i></div><img src="/${esc(item.image)}" alt="${esc(item.imageAlt)}" width="1440" height="1000" loading="lazy"></div></div>`;
  return flowGraphic(['csi', 'ignition'].includes(item.slug) ? item.slug : item.title);
}

function caseRow(item, index) {
  return `<article class="project-row"><div class="project-info"><div class="project-topline"><span class="project-number">${String(index + 1).padStart(2, '0')}</span><span class="status"><span class="status-dot" aria-hidden="true"></span>${esc(item.status)}</span></div><div class="project-copy"><span class="eyebrow">${esc(item.category)}</span><h3><a href="/work/${esc(item.slug)}/">${esc(item.title)}</a></h3><p class="project-subtitle">${esc(item.subtitle)}</p><p class="description">${esc(item.summary)}</p></div><div class="project-bottom"><span>${esc(item.role)}</span><a class="text-link" href="/work/${esc(item.slug)}/">사례 자세히 보기 <span aria-hidden="true">↗</span></a></div></div><a class="project-visual-link" href="/work/${esc(item.slug)}/" aria-label="${esc(item.title)} 제작 사례 보기">${caseVisual(item)}<span class="visual-open" aria-hidden="true">↗</span></a></article>`;
}

const values = [
  ['필요한 것을 함께 정의합니다.', '현재 상황과 실제 사용자를 이해하고, 무엇을 만들지 구체적으로 정리합니다.'],
  ['같은 이해를 공유합니다.', '요구사항과 결정 이유, 진행 상황을 알기 쉽게 전달합니다.'],
  ['실제 쓰임을 확인합니다.', '작동하는 결과물을 보여주고, 사용할 때의 흐름을 함께 확인합니다.'],
  ['쉽게 사용할 수 있도록 전달합니다.', '운영 방법과 합의한 범위의 간단한 수정 방법까지 설명합니다.']
];
const valueRows = values.map(([title, description], n) => `<article class="value-row"><span class="row-number">0${n + 1}</span><h3>${title}</h3><p>${description}</p></article>`).join('');

const home = `<section class="hero wrap"><div class="hero-topline"><span class="eyebrow"><span class="blue-dot" aria-hidden="true"></span>INDEPENDENT PRODUCT STUDIO</span><span class="location">Seoul, Korea</span></div><div class="hero-composition"><div class="hero-copy"><h1>필요한 것을,<br><span>작동하는 제품으로.</span></h1><p>고객에게 필요한 것을 함께 정의하고,<br>실제로 사용할 수 있는 소프트웨어로 제작합니다.</p><a class="button" href="/contact/">제품 제작 상담하기 <span aria-hidden="true">↗</span></a></div><figure class="structure-visual"><figcaption>연결되어 돌아가는 구조</figcaption><div class="structure-grid"><div class="structure-node node-knowledge"><small>KNOWLEDGE</small><span>지식</span></div><div class="structure-node node-data"><small>DATA</small><span>데이터</span></div><div class="structure-node node-rules"><small>RULES</small><span>규칙</span></div><div class="structure-node node-product"><small>PRODUCT</small><span>제품</span><i aria-hidden="true">↗</i></div></div></figure></div><div class="hero-index"><span>정의하고</span><span>구조를 만들고</span><span>제품으로 구현하고</span><span>쉽게 전달합니다</span></div></section>
<section class="section wrap selected-work">${sectionHead('01', 'SELECTED WORK', '필요가 달랐습니다.<br>만드는 구조도 달랐습니다.', '대표 박민석이 직접 제작하거나 팀에서 맡아 진행한 프로젝트입니다.')}${cases.filter(item => item.featured).map((item, n) => caseRow(item, n)).join('')}<a class="text-link section-end-link" href="/work/">모든 제작 사례 보기 <span aria-hidden="true">↗</span></a></section>
<section class="philosophy-section"><div class="wrap philosophy-layout"><div><span class="eyebrow">02 / OUR PHILOSOPHY</span><h2>일이 돌아가려면,<br>연결되어야 합니다.</h2></div><div class="philosophy-copy"><p class="large-copy">제품, 지식, 데이터, 규칙을 연결해<br>일이 돌아가는 구조를 만듭니다.</p><p>누가 무엇을 해야 하는지, 어떤 정보가 필요한지, 어떤 기준으로 결정하는지. 이 흐름을 이해하고 소프트웨어에 담는 것이 타입웍스의 일입니다.</p><a class="text-link" href="/about/">타입웍스의 생각과 원칙 <span aria-hidden="true">↗</span></a></div></div></section>
<section class="section wrap service-overview">${sectionHead('03', 'WHAT WE MAKE', '고객의 일에 맞춘 제품을 만듭니다.')}<div class="service-list"><a href="/services/#custom"><span class="row-number">01</span><h3>맞춤 소프트웨어</h3><p>필요한 기능을 갖춘 웹 서비스와 프로토타입</p><span aria-hidden="true">↗</span></a><a href="/services/#operations"><span class="row-number">02</span><h3>업무 도구와 AI 적용</h3><p>반복 업무, 지식과 데이터의 흐름을 정리하는 도구</p><span aria-hidden="true">↗</span></a><a href="/services/#events"><span class="row-number">03</span><h3>공연과 현장 시스템</h3><p>관객 참여와 행사 운영을 연결하는 제품</p><span aria-hidden="true">↗</span></a></div>${technologySection}<div class="handover-note"><span class="eyebrow">MADE TO BE USED</span><p>만들고, 쓰는 방법까지.<br><span>운영과 간단한 수정 방법을 이해하기 쉽게 알려드립니다.</span></p><a class="text-link" href="/services/#handover">제작과 인수인계 안내 <span aria-hidden="true">↗</span></a></div></section>${cta()}`;

const about = `${pageIntro('ABOUT TYPEWORKS', '일이 돌아가는 구조를<br>만드는 회사입니다.', '타입웍스는 대표 박민석이 이끄는 소프트웨어 제작 스튜디오입니다.<br>사용자의 필요를 이해하고, 제품과 운영의 흐름을 함께 만듭니다.')}
<section class="section wrap belief-section">${sectionHead('01', 'PHILOSOPHY & MISSION', '연결이 실제 쓰임을 만듭니다.')}<div class="belief-layout"><p class="belief-statement">제품.<br>지식.<br>데이터.<br><span>규칙.</span></p><div class="belief-copy"><h3>우리의 철학</h3><p class="large-copy">제품, 지식, 데이터, 규칙을 연결해 일이 돌아가는 구조를 만듭니다.</p><p>정보가 있어도 서로 전달되지 않으면 같은 일을 반복하게 됩니다. 규칙이 있어도 실제 흐름에 담기지 않으면 적용하기 어렵습니다. 타입웍스는 필요한 요소를 이해하고, 사람들이 함께 사용할 수 있는 제품으로 연결합니다.</p><h3>지금 하는 일</h3><p>고객에게 필요한 것을 함께 정의하고, 실제로 사용할 수 있는 소프트웨어로 제작합니다. 제작한 제품을 운영하고 간단히 수정하는 방법까지 쉽게 전달합니다.</p></div></div></section>
<section class="section wrap values-section">${sectionHead('02', 'HOW WE WORK', '철학은 일하는 방식으로 드러납니다.')}<div class="values-list">${valueRows}</div></section>
<section class="founder-section"><div class="wrap founder-layout"><div><span class="eyebrow">03 / FOUNDER</span><h2>박민석<span>대표 / 제품 제작자</span></h2><p class="founder-line">요구를 구체화하고,<br>일을 구조화하고,<br>제품으로 전달합니다.</p>${external('https://www.linkedin.com/in/type-types', '대표 소개 보기')}</div><div class="founder-copy"><p>AI 대화 제품의 프로토타입과 팀 운영, 연구팀을 위한 데이터 도구, 동아리 운영 시스템과 공연 참여 모듈을 경험했습니다.</p><p>서로 다른 분야의 사람들이 무엇을 필요로 하는지 이해하고, 화면과 기능으로 구체화하는 작업에 관심을 두고 있습니다. 흩어진 지식과 정보를 함께 이해할 수 있는 구조로 정리하는 일도 중요하게 생각합니다.</p><dl class="experience-list"><div><dt>제품 제작</dt><dd>멜리사, 온담, K-NET, 공연 참여 모듈</dd></div><div><dt>연구팀 협업</dt><dd>CSI 데이터 수집과 라벨링, 영상의학 학습, 병리 이미지 편집</dd></div><div><dt>교육과 전달</dt><dd>코딩 교육, 제작물 설명, 시연과 발표</dd></div></dl><a class="text-link" href="/work/">프로젝트별 역할과 결과 <span aria-hidden="true">↗</span></a></div></div></section>
<section class="section wrap vision-section">${sectionHead('04', 'OUR DIRECTION', '만드는 경험을 더 많은 사람에게.')}<p class="vision-statement">자신의 필요를 정의하고,<br>기술로 해결하며,<br>배운 것을 함께 나눌 수 있도록.</p><div class="direction-list"><article><span class="eyebrow">TODAY</span><h3>제품 제작</h3><p>고객에게 필요한 소프트웨어를 함께 정의하고 제작합니다. 현재 타입웍스의 중심 사업입니다.</p></article><article><span class="eyebrow">EXPERIENCE TO SHARE</span><h3>교육</h3><p>AI와 소프트웨어를 활용하고, 직접 만들고 수정하는 방법을 쉽게 전달하는 교육으로 경험을 넓혀갑니다.</p></article><article><span class="eyebrow">FUTURE VISION</span><h3>AI 학원 설립과 운영</h3><p>초중학생을 중심으로 필요한 것을 정의하고, AI를 활용해 제품을 만들고 발표하는 학원을 구상하고 있습니다. 지식 공유와 소통, 존중과 책임을 함께 배웁니다.</p><span class="state-note">설립을 구상하는 단계입니다.</span></article></div></section>${cta()}`;

const services = `${pageIntro('PRODUCT DEVELOPMENT', '필요한 것을 정의하고,<br>소프트웨어로 만듭니다.', '처음부터 완성된 기획서를 준비하실 필요는 없습니다.<br>현재의 불편과 원하는 결과를 들려주세요. 필요한 범위를 함께 정리합니다.')}
<section class="section wrap service-details">${sectionHead('01', 'WHAT WE CAN BUILD', '이런 제작을 맡길 수 있습니다.')}<article id="custom" class="service-detail"><span class="row-number">01</span><div><h3>맞춤 소프트웨어</h3><p class="large-copy">아이디어와 요구를<br>사용할 수 있는 제품으로.</p></div><div><p>사용할 사람과 필요한 기능을 정의하고, 웹 서비스나 프로토타입으로 제작합니다. 화면 설계와 기능 구현, 사용 흐름 확인을 함께 진행합니다.</p><ul><li>신규 서비스와 제품 프로토타입</li><li>신청, 예약, 회원 및 관리자 기능</li><li>AI 대화와 정보 활용 기능</li></ul><a class="text-link" href="/work/ondam/">온담 제작 경험 보기 <span aria-hidden="true">↗</span></a></div></article>
<article id="operations" class="service-detail"><span class="row-number">02</span><div><h3>업무 도구와 AI 적용</h3><p class="large-copy">정보와 반복 업무를<br>하나의 흐름으로.</p></div><div><p>흩어진 정보를 모으고, 업무의 단계와 규칙을 도구에 담습니다. 필요한 곳에 AI를 적용하고, 수집한 데이터가 실제 작업에 쓰이도록 연결합니다.</p><ul><li>모집, 승인, 일정과 팀 운영 도구</li><li>지식 정리와 검색, AI 활용 기능</li><li>연구 데이터 수집과 라벨링 도구</li></ul><a class="text-link" href="/work/csi/">CSI 데이터 도구 보기 <span aria-hidden="true">↗</span></a></div></article>
<article id="events" class="service-detail"><span class="row-number">03</span><div><h3>공연과 현장 시스템</h3><p class="large-copy">운영자와 참여자를<br>같은 경험 안으로.</p></div><div><p>공연과 행사에서 참여자가 해야 하는 일, 운영자가 관리해야 하는 일을 연결합니다. 실제 현장의 진행 흐름에 맞춰 제품을 구성합니다.</p><ul><li>관객 응원, 채팅과 추첨</li><li>공연 진행 및 운영 화면</li><li>참가 신청과 현장 참여 기능</li></ul><a class="text-link" href="/work/ignition/">공연 현장 사용 사례 보기 <span aria-hidden="true">↗</span></a></div></article></section>
<div class="wrap">${technologySection}</div>
<section class="process-section"><div class="wrap">${sectionHead('02', 'THE PROCESS', '고객이 모든 작업을 정의할 필요는 없습니다.', '타입웍스가 상황과 요구를 정리하고, 고객은 필요한 판단과 확인에 참여합니다.')}<ol class="process-list"><li><span>01</span><h3>필요 이해</h3><p>현재 업무, 사용할 사람, 원하는 결과를 함께 확인합니다.</p></li><li><span>02</span><h3>범위 합의</h3><p>기능과 화면, 완료 기준, 일정과 비용을 정리합니다.</p></li><li><span>03</span><h3>제작과 확인</h3><p>작동하는 결과물을 보여드리고 필요한 선택을 쉽게 설명합니다.</p></li><li><span>04</span><h3>전달과 교육</h3><p>제품과 운영 방법, 합의한 수정 방법을 전달합니다.</p></li></ol></div></section>
<section class="section wrap budget-section">${sectionHead('03', 'PROJECT SCOPE & BUDGET', '예산과 기대치를 함께 맞춥니다.')}<div class="budget-layout"><div><p class="budget-caption">상담하고자 하는 프로젝트 규모</p><p class="budget-number">500<span>만</span> ~ 1,000<span>만 원</span></p><p class="description">제작 범위와 요구에 따라 개별 견적을 안내합니다.<br>위 금액은 고정 패키지 가격이 아닙니다.</p></div><div class="scope-checks"><h3>견적에서 함께 정하는 것</h3><dl><div><dt>만드는 범위</dt><dd>사용자, 기능과 화면, 외부 연동</dd></div><div><dt>기간과 완료 기준</dt><dd>일정, 중간 확인 지점, 전달할 결과물</dd></div><div><dt>수정 범위와 횟수</dt><dd>포함되는 수정과 추가 기능의 구분</dd></div><div><dt>교육과 운영 비용</dt><dd>설명할 수정 방법, 호스팅과 AI 사용료</dd></div></dl></div></div></section>
<section class="handover-section" id="handover"><div class="wrap handover-layout"><div><span class="eyebrow">04 / HANDOVER</span><h2>만드는 데서<br>쓰는 데까지.</h2></div><div><p class="large-copy">작은 수정과 운영 방법을<br>쉽고 간단하게 알려드립니다.</p><p>제작 전에 교육할 범위를 함께 정합니다. 내용을 어디에서 바꾸는지, 데이터를 어떻게 확인하는지, 운영 중 무엇을 살펴보는지 실제 제품으로 설명합니다.</p><p>제품을 이해하고 직접 다룰 수 있도록, 필요한 설명과 안내를 인수인계 범위에 포함합니다.</p></div></div></section>
<section class="section wrap faq-section">${sectionHead('05', 'QUESTIONS', '제작 전 궁금한 점')}<details><summary>기획서가 없어도 상담할 수 있나요?</summary><p>네. 현재의 불편과 원하는 결과부터 들려주세요. 타입웍스가 필요한 요구와 제작 범위를 함께 정리합니다.</p></details><details><summary>진행 중 기능을 추가하거나 바꿀 수 있나요?</summary><p>제작 전에 수정 범위와 횟수를 합의합니다. 새로운 기능이나 범위 변경이 필요하면 비용과 일정에 미치는 영향을 설명하고 함께 정합니다.</p></details><details><summary>제작 후 직접 수정할 수 있나요?</summary><p>합의한 범위의 수정 방법을 쉽게 설명해 드립니다. 어떤 내용을 직접 바꾸고, 어떤 변경에 개발이 필요한지 제작 전에 함께 확인합니다.</p></details></section>${cta()}`;

const work = `${pageIntro('SELECTED WORK', '사람의 필요를<br>제품의 구조로.', '서로 다른 사용자의 요구를 화면과 기능으로 구체화한 경험입니다.<br>각 사례에서 맡은 역할과 실제 제작 범위를 확인하실 수 있습니다.')}<section class="section wrap work-list"><p class="case-provenance">대표의 기존 프로젝트 참여 경험을 포함합니다. 팀 프로젝트는 담당 역할과 팀의 결과를 구분해 소개합니다.</p>${cases.map((item, n) => caseRow(item, n)).join('')}</section>${cta('이런 도구가 필요하셨나요?<br>상황부터 들려주세요.')}`;

const contact = `${pageIntro('START A CONVERSATION', '어떤 것이<br>필요하신가요?', '현재 상황과 원하는 결과를 알려주세요.<br>무엇을 만들면 좋을지, 어느 범위로 시작할지 함께 이야기하겠습니다.')}
<section class="section wrap contact-layout"><aside class="contact-aside"><h2>완성된 기획서보다,<br>현재의 이야기부터.</h2><p>누가 사용할지, 어떤 일이 불편한지, 무엇이 달라졌으면 하는지 설명해 주세요.</p><div class="contact-route"><span class="eyebrow">CONTACT</span>${recipient ? external('mailto:' + recipient, esc(recipient), 'contact-address') : external('https://www.linkedin.com/in/type-types', 'LinkedIn으로 연락하기', 'contact-address')}<p>${recipient ? '이메일 앱에서 작성한 내용을 확인하고 보내실 수 있습니다.' : '상담 내용을 작성해 복사한 뒤 LinkedIn 메시지로 전달해 주세요.'}</p></div><p class="contact-budget">프로젝트 규모: 500만~1,000만원 중심<br>기능과 범위를 확인한 뒤 개별 견적을 안내합니다.</p></aside>
<form id="inquiry-form" class="inquiry-form" data-recipient="${esc(recipient)}"><div class="form-heading"><h2>제작 상담 내용</h2><span>필수 항목 *</span></div><div class="form-pair"><div class="field"><label for="inquiry-name">이름 *</label><input id="inquiry-name" name="name" autocomplete="name" required maxlength="100" placeholder="성함을 알려주세요"></div><div class="field"><label for="inquiry-organization">회사 또는 소속</label><input id="inquiry-organization" name="organization" autocomplete="organization" maxlength="150" placeholder="회사, 연구팀, 단체 등"></div></div><div class="field"><label for="inquiry-email">이메일 *</label><input id="inquiry-email" type="email" name="email" autocomplete="email" required maxlength="254" placeholder="답변을 받을 이메일"></div><div class="field"><label for="inquiry-problem">현재 상황과 불편 *</label><textarea id="inquiry-problem" name="problem" required rows="4" maxlength="5000" placeholder="지금 어떤 일을 어떻게 하고 계신가요?"></textarea></div><div class="field"><label for="inquiry-outcome">원하는 결과</label><textarea id="inquiry-outcome" name="outcome" rows="3" maxlength="5000" placeholder="누가 사용할지, 무엇이 달라졌으면 하는지 알려주세요."></textarea></div><div class="form-pair"><div class="field"><label for="inquiry-budget">생각하시는 예산</label><select id="inquiry-budget" name="budget"><option value="">아직 정하지 않았습니다</option value="under-500">500만원 미만</option><option value="500-1000">500만~1,000만원</option><option value="1000-plus">1,000만원 이상</option></select></div><div class="field"><label for="inquiry-timing">희망 일정</label><input id="inquiry-timing" name="timing" maxlength="200" placeholder="예: 12월 시작, 일정 협의"></div></div><p class="form-note">입력 내용은 이 화면에서 상담 요약을 만드는 데 사용됩니다. 내용을 전달하려면 아래 연락 경로로 직접 보내주세요.</p><div class="form-actions">${recipient ? '<button id="email-inquiry" class="button" type="submit">이메일로 상담 보내기 <span aria-hidden="true">↗</span></button>' : ''}<button id="copy-inquiry" class="button${recipient ? ' secondary' : ''}" type="button">상담 내용 복사하기 <span aria-hidden="true">↗</span></button>${!recipient ? external('https://www.linkedin.com/in/type-types', 'LinkedIn 열기', 'text-link') : ''}</div><p id="inquiry-status" class="form-status" role="status" aria-live="polite"></p><div id="draft-panel" class="draft-panel" hidden><label for="inquiry-draft">전달할 상담 요약</label><textarea id="inquiry-draft" readonly rows="12"></textarea><p>내용을 복사해 연락 채널로 보내주세요.</p></div><noscript><p>상담 요약을 만들려면 JavaScript를 켜주세요. 위 연락 경로로 바로 상담 내용을 보내셔도 됩니다.</p></noscript></form></section>`;

function detail(item) {
  const links = item.links.map(link => external(link.url, esc(link.label))).join('');
  const next = cases[(cases.indexOf(item) + 1) % cases.length];
  return `<section class="page-intro case-intro wrap"><a class="back-link" href="/work/">← 모든 제작 사례</a><div class="case-topline"><span class="eyebrow">${esc(item.category)}</span><span class="status"><span class="status-dot" aria-hidden="true"></span>${esc(item.status)}</span></div><h1>${esc(item.title)}</h1><p class="case-subtitle">${esc(item.subtitle)}</p><p class="intro-description">${esc(item.summary)}</p><div class="case-role"><span>담당 역할</span><p>${esc(item.role)}</p></div></section><div class="case-hero-visual wrap">${caseVisual(item)}</div><section class="section wrap case-story"><article><span class="eyebrow">01 / THE NEED</span><h2>무엇이 필요했나요?</h2><p>${esc(item.problem)}</p></article><article><span class="eyebrow">02 / THE WORK</span><h2>어떻게 만들었나요?</h2><ol>${item.approach.map(line => `<li>${esc(line)}</li>`).join('')}</ol></article><article><span class="eyebrow">03 / THE RESULT</span><h2>무엇을 전달했나요?</h2><p>${esc(item.result)}</p><div class="case-links">${links}</div></article></section><div class="case-next wrap"><a href="/work/">모든 제작 사례</a><a href="/work/${esc(next.slug)}/">다음 사례: ${esc(next.title)} <span aria-hidden="true">→</span></a></div>${cta()}`;
}

const pages = [
  ['index.html', '/', '필요한 것을 작동하는 제품으로', '타입웍스는 고객에게 필요한 것을 함께 정의하고 소프트웨어로 제작합니다. 맞춤 제품, 업무 도구와 AI 적용, 공연 시스템 제작과 쉬운 운영 교육.', home],
  ['about/index.html', '/about/', '회사 소개', '제품, 지식, 데이터, 규칙을 연결해 일이 돌아가는 구조를 만드는 타입웍스의 철학, 작업 원칙과 비전.', about],
  ['services/index.html', '/services/', '제품 제작', '맞춤 소프트웨어, 업무 도구와 AI 적용, 공연 시스템 제작. 진행 방식, 예산과 범위, 수정 및 인수인계 안내.', services],
  ['work/index.html', '/work/', '제작 사례', 'K-NET, CSI 데이터 도구, 공연 참여 모듈, 멜리사와 온담 등 대표 박민석의 프로젝트 역할과 제작 경험.', work],
  ['contact/index.html', '/contact/', '제작 상담', '현재의 불편과 원하는 결과를 들려주세요. 타입웍스와 필요한 소프트웨어의 범위와 예산을 함께 이야기하세요.', contact],
  ...cases.map(item => [`work/${item.slug}/index.html`, `/work/${item.slug}/`, item.title + ' 제작 사례', item.summary, detail(item)])
];

function document(title, description, path, body) {
  const active = path.startsWith('/work/') ? '/work/' : path;
  return `<!doctype html>
<html lang="ko">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)} | Typeworks</title><meta name="description" content="${esc(description)}">
<meta name="theme-color" content="#f7f7f2"><link rel="canonical" href="https://typeworks.pro${path}">
<meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:site_name" content="Typeworks"><meta property="og:title" content="${esc(title)} | Typeworks"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="https://typeworks.pro${path}"><meta property="og:image" content="https://typeworks.pro/assets/og-image.png">
<meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png"><link rel="manifest" href="/site.webmanifest">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script>
<script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@type': 'Organization', name: 'Typeworks', alternateName: '타입웍스', url: 'https://typeworks.pro/', logo: 'https://typeworks.pro/assets/brand-mark.svg', description: '제품, 지식, 데이터, 규칙을 연결해 일이 돌아가는 구조를 만듭니다.', founder: { '@type': 'Person', name: '박민석', alternateName: 'Minseok Park' }, sameAs: ['https://www.linkedin.com/in/type-types'] })}</script>
</head><body data-menu-open="false">${header(active)}<main id="main" tabindex="-1">${body}</main>${footer}</body>
</html>
`;
}

for (const [file, path, title, description, body] of pages) {
  const destination = resolve(root, file);
  await mkdir(dirname(destination), { recursive: true });
  await writeFile(destination, document(title, description, path, body));
}
const notFound = `${pageIntro('404 / PAGE NOT FOUND', '찾으시는 페이지가<br>보이지 않습니다.', '주소를 확인하시거나 홈에서 필요한 내용을 찾아주세요.')}<div class="wrap not-found-action"><a class="button" href="/">타입웍스 홈으로 <span aria-hidden="true">↗</span></a></div>`;
await writeFile(resolve(root, '404.html'), document('페이지를 찾을 수 없습니다', '타입웍스 홈에서 제작 서비스와 사례를 확인하세요.', '/', notFound).replace('<meta name="theme-color"', '<meta name="robots" content="noindex"><meta name="theme-color"'));
const paths = [...pages.map(page => page[1]), '/en/'];
await writeFile(resolve(root, 'sitemap.xml'), '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + paths.map(path => `  <url><loc>https://typeworks.pro${path}</loc></url>`).join('\n') + '\n</urlset>\n');
console.log('Generated ' + pages.length + ' pages, 404 and sitemap.');
